# Generated by Django 4.2.2 on 2023-07-03 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100000)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime)),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
